#------------------------------------------------------
# Copyright (c) 2025, Elehobica
# Released under the BSD-2-Clause
# refer to https://opensource.org/licenses/BSD-2-Clause
#------------------------------------------------------

name: Build Binaries

on: 
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-binaries:
    strategy:
      matrix:
        project: [sine_wave_i2s_32b]
        build: [build, build2]
        include:
          - build: build
            platform: rp2040
            board: pico
          - build: build2
            platform: rp2350
            board: pico2
    runs-on: ubuntu-latest
    env:
      RELEASE_DIR: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        uses: ./.github/actions/build-and-rename
        with:
          path: samples/${{ matrix.project }}
          build: ${{ matrix.build }}
          platform: ${{ matrix.platform }}
          board: ${{ matrix.board }}
          identifier: ${{ matrix.board}}
          output_path: ${{ env.RELEASE_DIR }}
      - name: Analyze binary size
        run: |
          echo "=== Binary Analysis for ${{ matrix.board }} ===" 
          if [ -f "${{ env.RELEASE_DIR }}/sine_wave_i2s_32b_${{ matrix.board }}.elf" ]; then
            arm-none-eabi-size "${{ env.RELEASE_DIR }}/sine_wave_i2s_32b_${{ matrix.board }}.elf"
            echo ""
            echo "Top symbols by size:"
            arm-none-eabi-nm --size-sort "${{ env.RELEASE_DIR }}/sine_wave_i2s_32b_${{ matrix.board }}.elf" | tail -10
          fi

      - name: Upload production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-binaries-${{ matrix.project }}-${{ matrix.board }}
          path: |
            ${{ env.RELEASE_DIR }}/*.uf2
            ${{ env.RELEASE_DIR }}/*.elf
          retention-days: 30

  release-tag-condition:
    runs-on: ubuntu-latest
    outputs:
      matched: ${{ steps.check.outputs.matched }}
    steps:
      - name: Check if Release Tag Condition Matched
        id: check
        run: |
          if [[ ${{ github.ref_type }} == 'tag' && ${{ github.ref_name }} =~ ^[0-9]+.[0-9]+.[0-9]+$ ]]; then
            echo "matched=true" >> $GITHUB_OUTPUT
            echo "Release tag condition matched"
          else
            echo "matched=false" >> $GITHUB_OUTPUT
            echo "Release tag condition not matched"
          fi

  call-upload-release-asset:
    needs: [build-binaries, release-tag-condition]
    if: ${{ needs.release-tag-condition.outputs.matched == 'true' }}
    uses: ./.github/workflows/upload-release-asset.yml
    with:
      source_run_id: ${{ github.run_id }}
      artifacts_dirs: "dist-binaries-*"
